image: gitpod/workspace-full-vnc

tasks:
  - init: npm install && npm run build
    command: npm run start

vscode:
  extensions:
    - christian-kohler.npm-intellisense@1.2.2:OXx6idzXSYM8yU/TAjgFOw==